# Enable logger module
CONFIG_LOG=y

# Enable BLE stack
CONFIG_BT=y

CONFIG_BT_DEVICE_NAME="ponyotemp"

# Increase stack size for the main thread and System Workqueue
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=2048
CONFIG_MAIN_STACK_SIZE=2048